import javax.swing.*;
import java.io.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class MainFrame extends JFrame {

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea = new java.awt.TextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        download = new javax.swing.JMenu();
        save = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        download.setText("Загрузить файл");
        download.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downloadMouseClicked(evt);
            }
        });
        jMenuBar1.add(download);

        save.setText("Сохранить файл");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        jMenuBar1.add(save);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textArea, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downloadMouseClicked
        JFileChooser fileopen = new JFileChooser();             
        int result = fileopen.showDialog(null, "Открыть файл"); //открываем диалог открытия файла
        if (result == JFileChooser.APPROVE_OPTION) 
        {
            File file = fileopen.getSelectedFile();
            try(FileReader reader = new FileReader(file)) //посимвольно считываем содержимое файла, затем записываем в текстАреа
                {
                    int c;
                    String s = "";
                    
                    while((c = reader.read())!=-1)
                    {
                        s += (char)c;
                    }    
                    textArea.setText(s);
                }
            catch(IOException ex)
                {
                    textArea.setText(ex.getMessage());
                }
        }
    }//GEN-LAST:event_downloadMouseClicked

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
         String s = textArea.getText(); //получаем текст из текстАреа
         
         int wordCount = 0; 
         int symbolCount = s.length();
         
         for(int i=0;i<s.length();i++) //вычитаем все символы пробелов и переносов
         {
             if(s.charAt(i)==' ') symbolCount--;
             if(s.charAt(i)=='\n') symbolCount-=2;       
         }
        
        Pattern pattern = Pattern.compile("[\\S]{1,}"); //ищем все непустые слова 
        Matcher matcher = pattern.matcher(s); 
         
         while(matcher.find())
         {
             wordCount++; 
         }
         
         File newFile = new File("TestFile.txt"); //создаем файл в папке с проектом
         try(FileWriter writer = new FileWriter("TestFile.txt", false))
        {
            writer.write(s); //записываем в него строку из текстАреа
            writer.flush();
        }
        catch(IOException ex){
             
           textArea.setText(ex.getMessage());
        } 
         
         String message = "Сохранение прошло успешно. В файл записано: " 
                 + symbolCount + " символов без учета пробелов и переносов строк и " + wordCount + " слов. ";
         JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_saveMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println("Закрыл");
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("Закрыл");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu download;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu save;
    private java.awt.TextArea textArea;
    // End of variables declaration//GEN-END:variables
}
